import type { ReactNode } from 'react';
import "../App.css";
import NavBar from '../components/NavBar';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="app">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}