import type { ReactNode } from 'react';
import "../App.css";
import NavBar from '../components/NavBar';
import { BrowserRouter } from 'react-router-dom';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <BrowserRouter>
          <div className="app">
            <NavBar />
            {children}
          </div>
        </BrowserRouter>
      </body>
    </html>
  );
}